# Generated by Django 5.1.5 on 2025-01-28 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='productImages/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryID', to='api.category')),
            ],
        ),
    ]
